### ISSUE TITLE
Problem with kodi 17.0 Krypton

### ISSUE THREAD

**Issue by mrvaita** [Ideneal/plugin.video.skystreaming#1]
I observe this error while playing the addon on Kodi 17.0 Krypto.

I just type the traceback because I was only able to visualize the log file within kodi. I'm sorry for that

ERROR: Unable to find plugin -->End of Python script error report<--
AttributeError: 'module' object has no attribute 'PLAYER_CORE_DVDPLAYER' xbmc.Player(xbmc.PLAYER_CORE_DVDPLAYER).play(url, item)
file "/storage/.kodi/addons/plugin.video.skystreaming/resources/lib/plugin.py" line 103, in play_channel

I hope that's enough information

**Comment by Ideneal** [comment]
Added support for kodi 17 in the [release 0.9.0](https://github.com/Ideneal/plugin.video.skystreaming/releases/tag/0.9.0)
